<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo6 Testes não paramétricos | Estatística Aplicada à Pesquisa</title>
  <meta name="description" content="Esse é um material auxiliar para o curso de Ciências de Dados aplicada à Saúde." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo6 Testes não paramétricos | Estatística Aplicada à Pesquisa" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Esse é um material auxiliar para o curso de Ciências de Dados aplicada à Saúde." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo6 Testes não paramétricos | Estatística Aplicada à Pesquisa" />
  
  <meta name="twitter:description" content="Esse é um material auxiliar para o curso de Ciências de Dados aplicada à Saúde." />
  

<meta name="author" content="Agatha Rodrigues" />


<meta name="date" content="2020-11-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="param.html"/>
<link rel="next" href="qualis.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Estatística Aplicada à Pesquisa </a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Sobre esse livro</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#sobre-mim"><i class="fa fa-check"></i><b>1.1</b> Sobre mim</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introdução</a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#bases-de-dados"><i class="fa fa-check"></i><b>2.1</b> Bases de dados</a><ul>
<li class="chapter" data-level="2.1.1" data-path="intro.html"><a href="intro.html#dados_gemelares"><i class="fa fa-check"></i><b>2.1.1</b> Gestações gemelares</a></li>
<li class="chapter" data-level="2.1.2" data-path="intro.html"><a href="intro.html#gestações-gemelares---depressão-e-amamentação"><i class="fa fa-check"></i><b>2.1.2</b> Gestações gemelares - depressão e amamentação</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#sobre-o-software-r"><i class="fa fa-check"></i><b>2.2</b> Sobre o software R</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#instalação-r-e-rstudio"><i class="fa fa-check"></i><b>2.3</b> Instalação R e RStudio</a><ul>
<li class="chapter" data-level="2.3.1" data-path="intro.html"><a href="intro.html#instalação-r"><i class="fa fa-check"></i><b>2.3.1</b> Instalação R</a></li>
<li class="chapter" data-level="2.3.2" data-path="intro.html"><a href="intro.html#instalação-rstudio"><i class="fa fa-check"></i><b>2.3.2</b> Instalação RStudio</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#primeiros-passos-com-r-e-rstudio."><i class="fa fa-check"></i><b>2.4</b> Primeiros passos com R e RStudio.</a><ul>
<li class="chapter" data-level="2.4.1" data-path="intro.html"><a href="intro.html#primeiros-contatos-com-rstudio"><i class="fa fa-check"></i><b>2.4.1</b> Primeiros contatos com RStudio</a></li>
<li class="chapter" data-level="2.4.2" data-path="intro.html"><a href="intro.html#primeiros-passos-no-r"><i class="fa fa-check"></i><b>2.4.2</b> Primeiros passos no R</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="intro.html"><a href="intro.html#como-obter-ajuda-no-r"><i class="fa fa-check"></i><b>2.5</b> Como obter ajuda no R</a></li>
<li class="chapter" data-level="2.6" data-path="intro.html"><a href="intro.html#pacotes"><i class="fa fa-check"></i><b>2.6</b> Pacotes</a><ul>
<li class="chapter" data-level="2.6.1" data-path="intro.html"><a href="intro.html#instalação"><i class="fa fa-check"></i><b>2.6.1</b> Instalação</a></li>
<li class="chapter" data-level="2.6.2" data-path="intro.html"><a href="intro.html#carregar-pacotes"><i class="fa fa-check"></i><b>2.6.2</b> Carregar pacotes:</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="intro.html"><a href="intro.html#materiais-complementares"><i class="fa fa-check"></i><b>2.7</b> Materiais complementares</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="conceitos.html"><a href="conceitos.html"><i class="fa fa-check"></i><b>3</b> Conceitos iniciais</a><ul>
<li class="chapter" data-level="3.1" data-path="conceitos.html"><a href="conceitos.html#população"><i class="fa fa-check"></i><b>3.1</b> População</a></li>
<li class="chapter" data-level="3.2" data-path="conceitos.html"><a href="conceitos.html#amostra"><i class="fa fa-check"></i><b>3.2</b> Amostra</a></li>
<li class="chapter" data-level="3.3" data-path="conceitos.html"><a href="conceitos.html#variaveis"><i class="fa fa-check"></i><b>3.3</b> Variáveis</a></li>
<li class="chapter" data-level="3.4" data-path="conceitos.html"><a href="conceitos.html#tabulação-de-dados"><i class="fa fa-check"></i><b>3.4</b> Tabulação de dados</a></li>
<li class="chapter" data-level="3.5" data-path="conceitos.html"><a href="conceitos.html#importação-de-dados-no-r"><i class="fa fa-check"></i><b>3.5</b> Importação de dados no R</a><ul>
<li class="chapter" data-level="3.5.1" data-path="conceitos.html"><a href="conceitos.html#extensão-.txt-ou-.csv"><i class="fa fa-check"></i><b>3.5.1</b> Extensão .txt ou .csv</a></li>
<li class="chapter" data-level="3.5.2" data-path="conceitos.html"><a href="conceitos.html#arquivos-em-excel"><i class="fa fa-check"></i><b>3.5.2</b> Arquivos em Excel</a></li>
<li class="chapter" data-level="3.5.3" data-path="conceitos.html"><a href="conceitos.html#arquivos-de-outros-softwares"><i class="fa fa-check"></i><b>3.5.3</b> Arquivos de outros softwares</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="conceitos.html"><a href="conceitos.html#consistencia"><i class="fa fa-check"></i><b>3.6</b> Análise de consistência e tratamento dos dados</a><ul>
<li class="chapter" data-level="3.6.1" data-path="conceitos.html"><a href="conceitos.html#importação-dos-dados"><i class="fa fa-check"></i><b>3.6.1</b> Importação dos dados</a></li>
<li class="chapter" data-level="3.6.2" data-path="conceitos.html"><a href="conceitos.html#arrumação-da-base-de-dados"><i class="fa fa-check"></i><b>3.6.2</b> Arrumação da base de dados</a></li>
<li class="chapter" data-level="3.6.3" data-path="conceitos.html"><a href="conceitos.html#identificação-de-casos-duplicados"><i class="fa fa-check"></i><b>3.6.3</b> Identificação de casos duplicados</a></li>
<li class="chapter" data-level="3.6.4" data-path="conceitos.html"><a href="conceitos.html#identificar-problemas-nas-variáveis-da-base-de-dados"><i class="fa fa-check"></i><b>3.6.4</b> Identificar problemas nas variáveis da base de dados</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="conceitos.html"><a href="conceitos.html#transformação-dos-dados"><i class="fa fa-check"></i><b>3.7</b> Transformação dos dados</a><ul>
<li class="chapter" data-level="3.7.1" data-path="conceitos.html"><a href="conceitos.html#transformação-de-variáveis-quantitativas"><i class="fa fa-check"></i><b>3.7.1</b> Transformação de variáveis quantitativas</a></li>
<li class="chapter" data-level="3.7.2" data-path="conceitos.html"><a href="conceitos.html#transformação-de-variáveis-qualitativas"><i class="fa fa-check"></i><b>3.7.2</b> Transformação de variáveis qualitativas</a></li>
<li class="chapter" data-level="3.7.3" data-path="conceitos.html"><a href="conceitos.html#manipulação-de-datas"><i class="fa fa-check"></i><b>3.7.3</b> Manipulação de datas</a></li>
<li class="chapter" data-level="3.7.4" data-path="conceitos.html"><a href="conceitos.html#filtragem-de-observações"><i class="fa fa-check"></i><b>3.7.4</b> Filtragem de observações</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="conceitos.html"><a href="conceitos.html#manipulando-os-formatos-das-bases-de-dados"><i class="fa fa-check"></i><b>3.8</b> Manipulando os formatos das bases de dados</a><ul>
<li class="chapter" data-level="3.8.1" data-path="conceitos.html"><a href="conceitos.html#combinando-bases-de-dados"><i class="fa fa-check"></i><b>3.8.1</b> Combinando bases de dados</a></li>
<li class="chapter" data-level="3.8.2" data-path="conceitos.html"><a href="conceitos.html#formato"><i class="fa fa-check"></i><b>3.8.2</b> Mudando formato da base de dado</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="conceitos.html"><a href="conceitos.html#exercícios"><i class="fa fa-check"></i><b>3.9</b> Exercícios</a><ul>
<li class="chapter" data-level="3.9.1" data-path="conceitos.html"><a href="conceitos.html#teóricos"><i class="fa fa-check"></i><b>3.9.1</b> Teóricos</a></li>
<li class="chapter" data-level="3.9.2" data-path="conceitos.html"><a href="conceitos.html#práticos-no-r"><i class="fa fa-check"></i><b>3.9.2</b> Práticos no R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="análise-exploratória-dos-dados.html"><a href="análise-exploratória-dos-dados.html"><i class="fa fa-check"></i><b>4</b> Análise exploratória dos dados</a><ul>
<li class="chapter" data-level="4.1" data-path="análise-exploratória-dos-dados.html"><a href="análise-exploratória-dos-dados.html#tabelas-de-frequências"><i class="fa fa-check"></i><b>4.1</b> Tabelas de frequências</a></li>
<li class="chapter" data-level="4.2" data-path="análise-exploratória-dos-dados.html"><a href="análise-exploratória-dos-dados.html#medidas-resumo"><i class="fa fa-check"></i><b>4.2</b> Medidas resumo</a><ul>
<li class="chapter" data-level="4.2.1" data-path="análise-exploratória-dos-dados.html"><a href="análise-exploratória-dos-dados.html#medidas-de-posição"><i class="fa fa-check"></i><b>4.2.1</b> Medidas de posição</a></li>
<li class="chapter" data-level="4.2.2" data-path="análise-exploratória-dos-dados.html"><a href="análise-exploratória-dos-dados.html#medidas-de-dispersão"><i class="fa fa-check"></i><b>4.2.2</b> Medidas de dispersão</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="análise-exploratória-dos-dados.html"><a href="análise-exploratória-dos-dados.html#tabelas"><i class="fa fa-check"></i><b>4.3</b> Tabelas cruzadas - duas variáveis qualitativas</a></li>
<li class="chapter" data-level="4.4" data-path="análise-exploratória-dos-dados.html"><a href="análise-exploratória-dos-dados.html#gráficos"><i class="fa fa-check"></i><b>4.4</b> Gráficos</a><ul>
<li class="chapter" data-level="4.4.1" data-path="análise-exploratória-dos-dados.html"><a href="análise-exploratória-dos-dados.html#pacote-ggplot2"><i class="fa fa-check"></i><b>4.4.1</b> Pacote ggplot2</a></li>
<li class="chapter" data-level="4.4.2" data-path="análise-exploratória-dos-dados.html"><a href="análise-exploratória-dos-dados.html#pacote-esquisse"><i class="fa fa-check"></i><b>4.4.2</b> Pacote esquisse</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="intro.html"><a href="intro.html#materiais-complementares"><i class="fa fa-check"></i><b>4.5</b> Materiais complementares</a></li>
<li class="chapter" data-level="4.6" data-path="conceitos.html"><a href="conceitos.html#exercícios"><i class="fa fa-check"></i><b>4.6</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="param.html"><a href="param.html"><i class="fa fa-check"></i><b>5</b> Testes paramétricos para média</a><ul>
<li class="chapter" data-level="5.1" data-path="param.html"><a href="param.html#teste-para-média-de-população-única"><i class="fa fa-check"></i><b>5.1</b> Teste para média de população única</a></li>
<li class="chapter" data-level="5.2" data-path="param.html"><a href="param.html#teste-para-comparação-de-médias-de-dois-grupos-independentes"><i class="fa fa-check"></i><b>5.2</b> Teste para comparação de médias de dois grupos independentes</a></li>
<li class="chapter" data-level="5.3" data-path="param.html"><a href="param.html#teste-para-comparação-de-médias-de-dois-grupos-dependentes"><i class="fa fa-check"></i><b>5.3</b> Teste para comparação de médias de dois grupos dependentes</a></li>
<li class="chapter" data-level="5.4" data-path="param.html"><a href="param.html#teste-para-comparação-de-mais-de-dois-grupos-independentes"><i class="fa fa-check"></i><b>5.4</b> Teste para comparação de mais de dois grupos independentes</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="nparam.html"><a href="nparam.html"><i class="fa fa-check"></i><b>6</b> Testes não paramétricos</a><ul>
<li class="chapter" data-level="6.1" data-path="nparam.html"><a href="nparam.html#teste-para-comparação-de-dois-grupos-independentes"><i class="fa fa-check"></i><b>6.1</b> Teste para comparação de dois grupos independentes</a></li>
<li class="chapter" data-level="6.2" data-path="nparam.html"><a href="nparam.html#teste-para-comparação-de-dois-grupos-dependentes"><i class="fa fa-check"></i><b>6.2</b> Teste para comparação de dois grupos dependentes</a></li>
<li class="chapter" data-level="6.3" data-path="param.html"><a href="param.html#teste-para-comparação-de-mais-de-dois-grupos-independentes"><i class="fa fa-check"></i><b>6.3</b> Teste para comparação de mais de dois grupos independentes</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="qualis.html"><a href="qualis.html"><i class="fa fa-check"></i><b>7</b> Associação entre variáveis qualitativas</a><ul>
<li class="chapter" data-level="7.1" data-path="qualis.html"><a href="qualis.html#testes-de-associação-entre-duas-variáveis-qualitativas"><i class="fa fa-check"></i><b>7.1</b> Testes de associação entre duas variáveis qualitativas</a></li>
<li class="chapter" data-level="7.2" data-path="qualis.html"><a href="qualis.html#medidas-de-associação"><i class="fa fa-check"></i><b>7.2</b> Medidas de associação</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="correlação-entre-variáveis-quantitativas.html"><a href="correlação-entre-variáveis-quantitativas.html"><i class="fa fa-check"></i><b>8</b> Correlação entre variáveis quantitativas</a></li>
<li class="chapter" data-level="9" data-path="análise-de-sobrevivência-uma-introdução.html"><a href="análise-de-sobrevivência-uma-introdução.html"><i class="fa fa-check"></i><b>9</b> Análise de sobrevivência - uma introdução</a></li>
<li class="chapter" data-level="" data-path="referências.html"><a href="referências.html"><i class="fa fa-check"></i>Referências</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estatística Aplicada à Pesquisa</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="nparam" class="section level1">
<h1><span class="header-section-number">Capítulo6</span> Testes não paramétricos</h1>
<p>Nesse capítulo, vamos discutir alguns testes de hipóteses não paramétricos.
Usaremos aqui já as informações sobre testes de hipóteses apresentadas em <a href="https://daslab-ufes.github.io/materiais/" class="uri">https://daslab-ufes.github.io/materiais/</a> no arquivo “Inferência Estatística”.</p>
<p>Os testes não paramétricos não fazem suposições a respeito da forma das distribuições e são baseados na ordem das observações. Os testes são construídos com base em seus postos na amostra.</p>
Considere os dados como exemplo: 8, 10, 2, 13, 4, 70. Para obter os postos, primeiro ordene os dados e atribua a cada observação a sua posição:
<div class="figure"><span id="fig:unnamed-chunk-186"></span>
<img src="figures/exemplo_posto.png" alt="Exemplo de posto" width="80%" />
<p class="caption">
Figure 6.1: Exemplo de posto
</p>
</div>
<p>Como consequência, os testes não levam em conta a distância entre os valores, apenas a ordem. E se há um valor muito discrepante dos demais isso não afeta o teste.</p>
<p>Vamos discutir nesse capítulo três testes paramétricos para comprar dois grupos independentes (Mann-Whitney), dois grupos dependentes (Wilcoxon) e mais de dois grupos independentes (Kruskal-Wallis).</p>
<div id="teste-para-comparação-de-dois-grupos-independentes" class="section level2">
<h2><span class="header-section-number">6.1</span> Teste para comparação de dois grupos independentes</h2>
<p>Considere que queremos comparar dois grupos com relação a uma variável quantitativa ou qualitativa ordinal. Um teste não paramétrico para a comparação dos dois grupos é o <strong>Mann-Whitney</strong>.</p>
<p>Como exemplo, considere que a obstetra do estudo sobre gemelares quer agora realizar uma análise apenas das gestações cuja gestante tenha até 21 anos. Vamos então carregar os pacotes que usaremos aqui, importar a base de dados e depois criar um novo objeto resultante da filtragem das gestantes mais novas.</p>
<p>Primeiramente, vamos carregar os pacotes que usaremos aqui.</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="nparam.html#cb312-1"></a><span class="kw">library</span>(readr) <span class="co">#leitor da base de dados csv</span></span>
<span id="cb312-2"><a href="nparam.html#cb312-2"></a><span class="kw">library</span>(dplyr) <span class="co">#para manipulação de dados</span></span>
<span id="cb312-3"><a href="nparam.html#cb312-3"></a><span class="kw">library</span>(tidyr) <span class="co">#para mudar formato da base de dados</span></span>
<span id="cb312-4"><a href="nparam.html#cb312-4"></a><span class="kw">library</span>(summarytools) <span class="co">#para medidas descritivas</span></span></code></pre></div>
<p>Importamos agora a base de dados gemelares e depois filtrar só as gestantes com até 21 anos.</p>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="nparam.html#cb313-1"></a>dados &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="dt">file =</span> <span class="st">&quot;dataset/dados_completos.csv&quot;</span>) <span class="co">#importando base de dados</span></span>
<span id="cb313-2"><a href="nparam.html#cb313-2"></a></span>
<span id="cb313-3"><a href="nparam.html#cb313-3"></a>dados_adoles &lt;-<span class="st"> </span><span class="kw">filter</span>(dados,idade<span class="op">&lt;=</span><span class="dv">21</span>) <span class="co">#filtrando só as gestantes até 21 anos</span></span>
<span id="cb313-4"><a href="nparam.html#cb313-4"></a><span class="kw">str</span>(dados_adoles) <span class="co">#ver as descrições das variáveis</span></span></code></pre></div>
<pre><code>## tibble [21 x 31] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ id                     : num [1:21] 14 20 22 23 26 27 30 35 42 51 ...
##  $ grupo                  : chr [1:21] &quot;placebo&quot; &quot;placebo&quot; &quot;progest&quot; &quot;progest&quot; ...
##  $ corion                 : chr [1:21] &quot;mono&quot; &quot;di&quot; &quot;di&quot; &quot;di&quot; ...
##  $ data_aval              : Date[1:21], format: &quot;2016-03-21&quot; &quot;2017-12-14&quot; ...
##  $ data_nascimento        : Date[1:21], format: &quot;1998-03-26&quot; &quot;1998-12-19&quot; ...
##  $ cor_branco             : chr [1:21] &quot;branca&quot; &quot;nbranca&quot; &quot;nbranca&quot; &quot;branca&quot; ...
##  $ peso_pre               : num [1:21] 48 61 100 61 71 58 94 47 107 65 ...
##  $ alt                    : num [1:21] 1.56 1.64 1.59 1.64 1.71 1.63 1.52 1.43 1.7 1.63 ...
##  $ gesta                  : num [1:21] 1 1 2 1 1 1 1 1 1 1 ...
##  $ para                   : num [1:21] 0 0 1 0 0 0 0 0 0 0 ...
##  $ aborto                 : num [1:21] 0 0 0 0 0 0 0 0 0 0 ...
##  $ ind_ap                 : chr [1:21] &quot;nao&quot; &quot;nao&quot; &quot;sim&quot; &quot;sim&quot; ...
##  $ tabagismo              : chr [1:21] &quot;nao&quot; &quot;nao&quot; &quot;nao&quot; &quot;nao&quot; ...
##  $ alcool                 : chr [1:21] &quot;nao&quot; &quot;nao&quot; &quot;sim&quot; &quot;nao&quot; ...
##  $ drogas                 : chr [1:21] &quot;nao&quot; &quot;nao&quot; &quot;nao&quot; &quot;nao&quot; ...
##  $ ig_aval                : num [1:21] 28.3 33.7 33.7 27.3 34.9 ...
##  $ medida_colo            : num [1:21] 20.7 7 12.1 37 16 28.6 11 10 34 18.3 ...
##  $ num_contra_ctg         : num [1:21] 1 10 3 2 10 2 6 5 8 9 ...
##  $ igp_semana             : num [1:21] 34 35 37 34 37 30 35 36 35 33 ...
##  $ igp_dia                : num [1:21] 6 3 6 1 3 2 1 2 3 5 ...
##  $ imc                    : num [1:21] 19.7 22.7 39.6 22.7 24.3 ...
##  $ igp                    : num [1:21] 34.9 35.4 37.9 34.1 37.4 ...
##  $ primigesta             : chr [1:21] &quot;sim&quot; &quot;sim&quot; &quot;nao&quot; &quot;sim&quot; ...
##  $ prematuridade          : chr [1:21] &quot;sim&quot; &quot;sim&quot; &quot;nao&quot; &quot;sim&quot; ...
##  $ idade                  : num [1:21] 17 18 20 18 17 18 21 18 18 20 ...
##  $ epds_antes             : num [1:21] 10 10 3 6 13 11 7 20 10 7 ...
##  $ epds_depois            : num [1:21] 9 8 4 8 16 11 15 29 10 5 ...
##  $ edps_antes_sn          : chr [1:21] &quot;nao&quot; &quot;nao&quot; &quot;nao&quot; &quot;nao&quot; ...
##  $ edps_depois_sn         : chr [1:21] &quot;nao&quot; &quot;nao&quot; &quot;nao&quot; &quot;nao&quot; ...
##  $ grupo_amamentacao      : chr [1:21] &quot;acompanhamento&quot; &quot;orientacao&quot; &quot;orientacao&quot; &quot;acompanhamento&quot; ...
##  $ tempo_amamentacao_meses: num [1:21] 16 15 8 17 10 2 8 16 9 15 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   id = col_double(),
##   ..   grupo = col_character(),
##   ..   corion = col_character(),
##   ..   data_aval = col_date(format = &quot;&quot;),
##   ..   data_nascimento = col_date(format = &quot;&quot;),
##   ..   cor_branco = col_character(),
##   ..   peso_pre = col_double(),
##   ..   alt = col_double(),
##   ..   gesta = col_double(),
##   ..   para = col_double(),
##   ..   aborto = col_double(),
##   ..   ind_ap = col_character(),
##   ..   tabagismo = col_character(),
##   ..   alcool = col_character(),
##   ..   drogas = col_character(),
##   ..   ig_aval = col_double(),
##   ..   medida_colo = col_double(),
##   ..   num_contra_ctg = col_double(),
##   ..   igp_semana = col_double(),
##   ..   igp_dia = col_double(),
##   ..   imc = col_double(),
##   ..   igp = col_double(),
##   ..   primigesta = col_character(),
##   ..   prematuridade = col_character(),
##   ..   idade = col_double(),
##   ..   epds_antes = col_double(),
##   ..   epds_depois = col_double(),
##   ..   edps_antes_sn = col_character(),
##   ..   edps_depois_sn = col_character(),
##   ..   grupo_amamentacao = col_character(),
##   ..   tempo_amamentacao_meses = col_double()
##   .. )</code></pre>
<p>Observamos que há <span class="math inline">\(n=21\)</span> observações na base de dados “dados_adoles”.</p>
<p>Agora, queremos comparar os grupos de progesterona e placebo com relação ao número de contrações. Ao observar a tabela de frequências do grupo, observamos que há apenas 9 observações no grupo placebo e 12 no grupo progesterona.</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="nparam.html#cb315-1"></a><span class="kw">freq</span>(dados_adoles<span class="op">$</span>grupo,<span class="dt">cumul=</span><span class="ot">FALSE</span>,<span class="dt">report.nas=</span><span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## Frequencies  
## 
##                 Freq        %
## ------------- ------ --------
##       placebo      9    42.86
##       progest     12    57.14
##         Total     21   100.00</code></pre>
<p>Vamos realizar o teste de Mann-Whitney. Para isso, a função que utilizamos é <code>wilcox.test</code> (não precisa instalar pacote). Essa função também será utilizada para comparação de grupos pareados e por isso precisamos informar ao R que, nesse caso, os grupos não são pareados ao colocar <code>paired=FALSE</code>.</p>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="nparam.html#cb317-1"></a><span class="kw">wilcox.test</span>(num_contra_ctg<span class="op">~</span>grupo,<span class="dt">data=</span>dados_adoles,<span class="dt">paired=</span><span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## 
## 	Wilcoxon rank sum test with continuity correction
## 
## data:  num_contra_ctg by grupo
## W = 59.5, p-value = 0.721
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>Como podemos observar, o valor p é grande e não há indícios para rejeição da hipótese nula de igualdade da distribuição do número de contrações nos dois grupos.</p>
</div>
<div id="teste-para-comparação-de-dois-grupos-dependentes" class="section level2">
<h2><span class="header-section-number">6.2</span> Teste para comparação de dois grupos dependentes</h2>
<p>Considere agora que temos dois grupos dependentes e queremos compará-los com relação a uma variável quantitativa ou qualitativa ordinal. A dependência entre os grupos pode ser devido a avaliar os mesmos indivíduos em dois momentos: antes e depois de uma intervenção.</p>
<p>Como exemplo, queremos comparar o escore médio de EPDS (depressão) antes e depois do parto das gestantes mais novas (até 21 anos). O teste de hipóteses para a comparação de dois grupos dependentes é conhecido como <strong>teste de Wilcoxon</strong>.</p>
<p>A função no R é a mesma que utilizamos no teste anterior, mas agora informamos ao R que os grupos são pareados ao utilizar o argumento <code>paired=TRUE</code>.</p>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="nparam.html#cb319-1"></a><span class="kw">wilcox.test</span>(dados_adoles<span class="op">$</span>epds_depois,dados_adoles<span class="op">$</span>epds_antes,<span class="dt">paired=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## 	Wilcoxon signed rank test with continuity correction
## 
## data:  dados_adoles$epds_depois and dados_adoles$epds_antes
## V = 139.5, p-value = 0.01952
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>Ao considerar o valor p do teste de Wilcoxon (0.01952), há indícios de diferença entre os dois momentos de avaliação do EPDS a um nível de significância de 5%.</p>
</div>
<div id="teste-para-comparação-de-mais-de-dois-grupos-independentes" class="section level2">
<h2><span class="header-section-number">6.3</span> Teste para comparação de mais de dois grupos independentes</h2>
<p>Em um cenário que queremos comparar uma variável quantitativa ou qualitativa ordinal de três ou mais grupos independentes, o teste não paramétrico é o teste de <strong>Kruskal-Wallis</strong>.</p>
<p>Agora apenas para as gestantes mais novas (dados_adoles), vamos comparar os três grupos de orientação sobre amamentação no pré-natal (acompanhamento, só orientação e nenhuma orientação) em relação ao tempo de amamentação. A função do R é a <code>kruskal.test</code>.</p>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="nparam.html#cb321-1"></a><span class="kw">kruskal.test</span>(tempo_amamentacao_meses<span class="op">~</span>grupo_amamentacao,<span class="dt">data=</span>dados_adoles)</span></code></pre></div>
<pre><code>## 
## 	Kruskal-Wallis rank sum test
## 
## data:  tempo_amamentacao_meses by grupo_amamentacao
## Kruskal-Wallis chi-squared = 2.5632, df = 2, p-value = 0.2776</code></pre>
<p>Como o valor p obtido é de 0.2776, não há indícios para rejeitar a hipótese de igualdade da distribuição do tempo de amamentação entre os três grupos.</p>
<p>Em um cenário que a hipótese nula do teste de Kruskal-Wallis é rejeitada, precisaríamos encontrar onde está essa diferença indicada na hipótese alternativa de Kruskal-Wallis. Para isso, realizaria uma análise de múltiplas comparações 2 a 2 grupos. No R, essa análise pode ser feita por meio da função <code>pairwise.wilcox.test</code> (não precisa instalar pacote).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="param.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="qualis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["livro_R_Agatha.pdf", "livro_R_Agatha.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
